# Generated by Django 5.1.4 on 2025-01-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_body_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='creationdate',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='creationdate',
            new_name='creation_date',
        ),
    ]
